### ISSUE TITLE
collapse macro/stage logging

### ISSUE THREAD

**Issue by jgangemi** [srevinsaju/togomak#31]
it would be nice if logging could be collapsed into something like `macro.stage` instead of the current format that duplicates the level, etc.

**Comment by srevinsaju** [comment]
Marking this as `wontfix`. This issue is fixed in togomak [modules](https://togomak.srev.in/docs/schema/module) and in [import](https://togomak.srev.in/docs/schema/import). Macros will be deprecated, both of them part of Togomak v2. For a guide on how to write a togomak module, see [this tutorial](https://togomak.srev.in/tutorial/creating-your-first-module)
